# Leave fields empty to use default values

[server]
# Currently supported:
# stikked: https://github.com/claudehohl/Stikked
# modernpaste (no longer maintained): https://github.com/LINKIWI/modern-paste
# server = "modernpaste"
server = "stikked"

# Submit URL of instance
# url = "https://paste.centos.org/api/create"
url = "https://paste.fedoraproject.org/api/paste/submit"

# File with list of sysinfo commands
commandfile = ""

[user]

# System user if empty
name = ""

# Pastes are private by default
private = 1
